MAM-3499-performance-image-transforming-decoding-and-caching
TheBLVD/mammoth pull request #189
Opened 2023-12-14 16:04 UTC by bnolens

https://linear.app/theblvd/issue/MAM-3499/performance-image-transforming-decoding-and-caching

2023-12-14 20:02 UTC, rileyhCode requested changes
A few questions/comments in the review.

2023-12-14 20:02 UTC, rileyhCode commented on Mammoth/Views/Cells/PostCardCell/PostCardProfilePic.swift
> +            }
This code/pattern is repeated a few times. Is it possible to encapsulate it?

2023-12-15 10:57 UTC, bnolens commented on Mammoth/Screens/DetailScreen/DetailViewModel.swift
> +                    }
I like that!

2023-12-15 10:58 UTC, bnolens commented on Mammoth/Models/PostCardModel.swift
> +        self.user?.clearCache()
Good point!

2023-12-15 11:08 UTC, bnolens commented on Mammoth/Views/Cells/PostCardCell/PostCardProfilePic.swift
> +            }
Not sure I see how to encapsulate this and really improve the code. 

Here's a function encapsulating the logic, but to me it make the code less readable. 

<img width="916" alt="Screenshot 2023-12-15 at 12 05 38" src="https://github.com/TheBLVD/mammoth/assets/221925/7cf5e7a3-7361-4b6d-9c76-f7e5dbe6dc4b">

2023-12-15 11:18 UTC, bnolens commented on Mammoth/Views/Cells/PostCardCell/PostCardProfilePic.swift
> +            }
Or as an UIImageView extension, which I like a little better already. 

<img width="1268" alt="Screenshot 2023-12-15 at 12 17 35" src="https://github.com/TheBLVD/mammoth/assets/221925/dbd12fa2-0000-406b-88b2-9acd1858497c">

2023-12-15 11:18 UTC, bnolens commented on Mammoth/Views/Cells/PostCardCell/PostCardProfilePic.swift
> +            }
Implementation: 
<img width="957" alt="Screenshot 2023-12-15 at 12 18 24" 
src="https://github.com/TheBLVD/mammoth/assets/221925/77a16ded-4b42-4135-b94a-ceb2b2d24ad9">

2023-12-15 11:25 UTC, bnolens commented on Mammoth/Views/Cells/PostCardCell/PostCardProfilePic.swift
> +            }
I ended up using the second version and pushed a commit with these changes

2023-12-15 18:12 UTC, rileyhCode approved these changes
LGTM

2023-12-15 18:12 UTC, merged