MAM-3521-performance-cache-cell-heights-and-associate-value-with
TheBLVD/mammoth pull request #197
Opened 2023-12-18 09:58 UTC by bnolens

https://linear.app/theblvd/issue/MAM-3521/performance-cache-cell-heights-and-associate-value-with-postcardmodel

2023-12-18 18:16 UTC, rileyhCode requested changes
A question about keeping/clearing the cellHeight during iPad rotation.

2023-12-18 18:16 UTC, rileyhCode commented on Mammoth/Models/PostCardModel.swift
> +    var cellHeight: CGFloat?
Does this get cleared out for the iPad rotation case?

2023-12-19 09:15 UTC, bnolens commented on Mammoth/Models/PostCardModel.swift
> +    var cellHeight: CGFloat?
Because this value is only used for the estimated cell height, it seems ok to leave it like this. In the case we clear it, it will rely on a fixed number (310 px) instead. This value is the same for all orientation and screen heights. So I don't see the value in adding this extra logic to invalidate the cached height. Am I missing something?

2023-12-19 16:09 UTC, rileyhCode commented on Mammoth/Models/PostCardModel.swift
> +    var cellHeight: CGFloat?
OK; that sounds good.

2023-12-19 16:10 UTC, rileyhCode approved these changes

2023-12-19 16:30 UTC, merged