MAM-3611-add-support-for-proton-mail
TheBLVD/mammoth pull request #232
Opened 2023-12-26 23:09 UTC by rileyhCode

- added support for Proton URL
- stop iterating over mail apps if there's a success
Annoyingly, Proton strips out the /n from the body (I even tried switching to \r to see if it made a difference; it didn't).

![95DA61B6-2ED9-44F4-B8F5-0DC8C34A9512_1_102_o](https://github.com/TheBLVD/mammoth/assets/13856393/1243a0d5-a23a-44a5-a2b7-d89c59ccbeaa)

2023-12-27 10:13 UTC, bnolens requested changes
Please review my comment.

2023-12-27 10:13 UTC, bnolens commented on Mammoth/Utils/EmailHandler.swift
> +                                return
The callback of `DispatchQueue.main.sync` is not returning anything. So I don't think you're aborting the for-loop early by returning here. What happens if multiple schemes are being opened?
You could use `await MainActor.run` instead which do return.

2023-12-27 19:27 UTC, rileyhCode commented on Mammoth/Utils/EmailHandler.swift
> +                                return
Good point. Made some changes; additional comments:

- have a static index into the Apps to try
- create a function to asynchronously try the next app in the list until there is a successful attempt
- added logging
- verified that if two of the apps are installed, only the first one in the list is notified

2023-12-28 16:46 UTC, bnolens approved these changes
LGTM

2023-12-28 16:46 UTC, bnolens commented on Mammoth/Utils/EmailHandler.swift
> -                    DispatchQueue.main.sync {
Another way would be to replace this line with `if let success = await MainActor.run { ...` and return if success is true.

2023-12-28 16:55 UTC, rileyhCode commented on Mammoth/Utils/EmailHandler.swift
> -                    DispatchQueue.main.sync {
I wasn't quite able to get it to work this way, because UIApplication.shared.open() is an async call with a  completion routine. Because of that, there was no way to return a 'success' bool to MainActor.run.

2023-12-28 16:58 UTC, merged