updated mastodonkit to include search changes.
TheBLVD/mammoth pull request #294
Opened 2024-01-14 18:04 UTC by derspyy

i couldn't tell if `resolve` should've been optional but i couldn't think of a situation in-app where it would've been false.

should close #287, question mark?

2024-01-14 18:24 UTC, derspyy commented
i can also add a function like `searchPost()` to MastodonKit to allow us to get a single post from its URL and a `getPostFromUrl()` or something like that on `SearchService` (similar to the old `searchAccount()`), which would help with quote posts.

2024-01-16 19:29 UTC, rileyhCode requested changes
I believe the goal of the PR is to fix #287 , correct? If so, I think we can just add this to Search.searchPosts():
`            Parameter(name: "resolve", value: "true")
`

2024-01-16 19:34 UTC, derspyy commented
well. the point is to match the mastodon api spec, that's only a consequence.

2024-01-17 17:56 UTC, derspyy commented
afaik, `v1/accounts/search` matches `@user@domain` and `v2/search` matches links.

2024-01-17 19:39 UTC, derspyy commented
(but for matching the username we are already using lookup)

2024-01-19 19:41 UTC, rileyhCode commented
The various search APIs are used in many disparate ways in the app (login instance search, Discover/search tab, looking up accounts, looking up posts, etc.). Because of this, I think it would be best if we can identify specific issues (like #287 above), and put up fixes for them. Ideally, these fixes will bring MastodonKit in line with the Mastodon APIs.

2024-01-20 16:41 UTC, derspyy commented
so you think it'd be better if i added those unused functions back in?

2024-01-20 16:43 UTC, derspyy commented
> I believe the goal of the PR is to fix #287 , correct? If so, I think we can just add this to Search.searchPosts():
> 
> `            Parameter(name: "resolve", value: "true")
> 
> `

i've renamed the issue to also address user urls, which is the other half of the pr.

2024-01-20 17:29 UTC, derspyy commented
the `Accounts.search()` url change was done because the spec says the old one's `resolve` param matches usernames, not urls. i've looked at the functions' usages throughout the code and didn't noticed anything that'd break. the only thing out of the blue was removing deprecated/unused functions which i think is a positive so we don't face this same problem in another interface later on.

2024-01-20 17:29 UTC, derspyy commented
anything else?

2024-01-22 22:29 UTC, rileyhCode requested changes

2024-01-22 22:29 UTC, rileyhCode commented on Mammoth/Services/Backend/MastodonKit/Requests/Accounts.swift
>          let toLimitBounds = between(1, and: 80, default: 40)
We should change this function name from search to searchAccounts so it better matches what it's doing.

2024-01-22 22:29 UTC, rileyhCode commented on Mammoth/Services/Backend/MastodonKit/Requests/Search.swift
> +            Parameter(name: "resolve", value: true),
The resolve parameter is already added below. If it should always be true, then it shouldn't be a parameter to this function.
The way it's currently set up, the caller can specify if they want to resolve it. Maybe some of the call sites need updating?

2024-01-22 22:31 UTC, derspyy commented on Mammoth/Services/Backend/MastodonKit/Requests/Accounts.swift
>          let toLimitBounds = between(1, and: 80, default: 40)
will do!
although i have to add it's used as `Accounts.search()`.

2024-01-22 22:31 UTC, derspyy commented on Mammoth/Services/Backend/MastodonKit/Requests/Search.swift
> +            Parameter(name: "resolve", value: true),
oh. got it.

2024-01-22 22:37 UTC, derspyy commented on Mammoth/Services/Backend/MastodonKit/Requests/Search.swift
> +            Parameter(name: "resolve", value: true),
i just noticed that it's set to true in all calls. i wonder why it doesn't resolve to a profile on the broader search results. are we doing individual requests for these?
![image](https://github.com/TheBLVD/mammoth/assets/65043391/bba138f6-dced-4069-a5a8-8b300c8650a4)

2024-01-22 23:09 UTC, derspyy commented
i thought of moving `searchAccounts` back to `Search.swift` since it's now using that endpoint. would that be less confusing?

2024-02-11 20:18 UTC, closed without merging