Only run filters and blocks client-side on remote feeds.
TheBLVD/mammoth pull request #428
Opened 2024-02-22 17:57 UTC by derspyy

this choice was made because on authenticated requests, these are handled by the server.

2024-02-22 19:37 UTC, bnolens requested changes

2024-02-22 19:37 UTC, bnolens commented on Mammoth/Screens/HomeScreen/NewsFeedViewModel+Services.swift
> +                    if case .community = type {
Also for `.channel(let type)`, right?

2024-02-23 00:18 UTC, derspyy commented on Mammoth/Screens/HomeScreen/NewsFeedViewModel+Services.swift
> +                    if case .community = type {
oh! are those... smart lists?

2024-02-23 12:43 UTC, bnolens commented on Mammoth/Screens/HomeScreen/NewsFeedViewModel+Services.swift
> +                    if case .community = type {
Yes

2024-02-23 12:44 UTC, bnolens commented on Mammoth/Screens/HomeScreen/NewsFeedViewModel+Services.swift
> +                    if case .community = type {
We called them channels before launch

2024-02-26 11:37 UTC, bnolens approved these changes
LGTM!

2024-02-26 20:09 UTC, merged