Localization.
TheBLVD/mammoth pull request #432
Opened 2024-02-26 12:23 UTC by derspyy

2024-02-26 15:49 UTC, rileyhCode commented on Mammoth/Localizable.xcstrings
> +            "value" : "Trensing"
Trensing -> Trending

2024-02-26 16:01 UTC, rileyhCode reviewed
Just a general note that the strings that depend on a count (e.g., post.likeCount) need a bit more work. There is some machinery in iOS to make it pick the correct value based on the # of items.

There's a more complete description of the issue here (although… I think the solution they present is a bit outdated, meaning Apple has made a more streamlined solution available): https://medium.com/@vitaliikuznetsov/plurals-localization-using-stringsdict-in-ios-a910aab8c28c

2024-02-26 17:43 UTC, derspyy commented
> Just a general note that the strings that depend on a count (e.g., post.likeCount) need a bit more work. There is some machinery in iOS to make it pick the correct value based on the # of items.
> 
> 
> 
> There's a more complete description of the issue here (although… I think the solution they present is a bit outdated, meaning Apple has made a more streamlined solution available): https://medium.com/@vitaliikuznetsov/plurals-localization-using-stringsdict-in-ios-a910aab8c28c

i'm currently using plurals internally. maybe they're not immediately visible as text, but on xcode, it's there.

2024-02-27 11:04 UTC, bnolens commented on Mammoth/Views/Cells/PostCardCell/PostCardMetadata.swift
> +        let like_localized = postCard.likeCount == "1" ? "post.likeCount.singular" : "post.likeCount.plural"
Wondering if this logic applies to all languages

2024-02-27 11:09 UTC, bnolens commented
Note to also translate strings in our info.plist. Thinking of the remote-notification warning for instance. Also App Store descriptions and In-app purchase labels (in IAPConfig).
What about push notification? Our NotificationService assumes notifications are in English.

2024-02-27 11:35 UTC, bnolens commented
Users should be able to change the app language in their settings. Does this Preferred Language setting work? 

https://github.com/TheBLVD/mammoth/assets/221925/304e8b51-e875-4cd7-90a7-6187882b1cf9

2024-02-27 13:49 UTC, derspyy commented
> What about push notification? Our NotificationService assumes notifications are in English.
> 
> 

hmm tough. we could either rework that, or move notifications to use, like, emojis? instead of text?

2024-02-27 21:56 UTC, derspyy commented on Mammoth/Views/Cells/PostCardCell/PostCardMetadata.swift
> +        let like_localized = postCard.likeCount == "1" ? "post.likeCount.singular" : "post.likeCount.plural"
worst case, they'll have an equivalent string for both, no? i mean, unless we change the number representation, in which case we just make that "1" a localized string.

2024-02-27 22:02 UTC, derspyy commented
> Users should be able to change the app language in their settings. Does this Preferred Language setting work?
> 
>  RPReplay_Final1709033609.MP4

is this already present? we'll need to go over these settings.

2024-02-28 09:27 UTC, bnolens commented
> > Users should be able to change the app language in their settings. Does this Preferred Language setting work?
> > RPReplay_Final1709033609.MP4
> 
> is this already present? we'll need to go over these settings.

It is already present yes

2024-03-01 10:59 UTC, bnolens commented
I rebased from main, enabled localization in Interface Builder files (for the onboarding) and added a JumpToNow translation key. 

https://github.com/TheBLVD/mammoth/assets/221925/3bc221de-7857-4277-85cb-8617611c69bc

2024-03-01 11:08 UTC, bnolens requested changes
I still see a considerable amount of strings not yet converted to NSLocalizedString. Not saying we should be close to 100% now but we're not yet in a place that can be shipped tbh. It's easy to test by forcing a non-translated language in the simulator and see which strings are not displayed as keys. See video. 

https://github.com/TheBLVD/mammoth/assets/221925/2dfea1ed-49ea-4332-b543-08b2dd8b6513

2024-03-01 21:07 UTC, derspyy commented
accidental force-push erasure. closing.

2024-03-01 21:07 UTC, closed without merging