Fix bookmark and favourite list scrolling
TheBLVD/mammoth pull request #435
Opened 2024-02-28 18:51 UTC by nickludlam

- Added `NewsFeedViewModel.makePaginatedRequest` to determine which feed types make paginated requests.
- Changed bookmarks and favourites to use `fetchAllPaginated()`
- Added `nextPageRange` and `previousPageRange` to NewsFeedViewModel to store our position in the paginated data
- Making paginated requests for unsupported feedTypes will throw the new `NewsFeedViewModelError.invalidFeedType`
- Removed cache hydration for all paginated feed types, as we cannot locate you correctly within the pages without storing the previous/next responses from the server. This intervention is made in `NewsFeedViewModel.syncDataSource()`. We still persist and retrieve the data, it is just ignored for now.
- Added a missing call to `shouldPollForListData` before `startPollingListData()`
- Added bookmarks to the exclude list of `shouldPollForListData` and `shouldSyncItems`
- One or two other minor fixes

2024-02-28 18:53 UTC, nickludlam commented
This should reference MAM-3869

2024-02-28 18:57 UTC, nickludlam commented
Things I'd like to improve:

- Retain the ability to use cached data, but always start you scrolling from the top
- Sync properly with any additions or removals you might make on the server outside of Mammoth (i.e. using the web client)
- Once you scroll to the bottom of the list, we disable the "pull up to load more" functionality, as the server has specifically told us no more information will be available. This is not the same as timeline data.

2024-02-29 16:04 UTC, bnolens requested changes
Awesome work! I left a few comments. I think there's a way you could simplify the code a little bit by having all requests return the same pagination object or enum, instead of the `cursorId` we currently are using. That way the NewsfeedViewModel stays a bit dumber and the code could be simplified a bit. 

This might increase a little bit the scale of this project, but it is a key part of the app so I think we need to be sure to tackle it the right way.

2024-02-29 16:04 UTC, bnolens commented on Mammoth/Screens/HomeScreen/NewsFeedViewModel.swift
> +    internal var makePaginatedRequest: Bool {
If all fetch requests return a `Paginated` object (as proposing in my other comment) the NewsFeedViewModel should not be aware of which request is paginated and which is not, it just sends the Paginated object and the fetch request knows how to handle it.

2024-02-29 16:04 UTC, bnolens commented on Mammoth/Screens/HomeScreen/NewsFeedViewModel.swift
> +    func fetchAllPaginated(range: RequestRange = .default, batchName: String, retryCount: Int = 0) async throws -> ([NewsFeedListItem], Pagination?, String?) {
If all fetch requests return a `Paginated` object, you don't need to split the fetch function in 2 anymore

2024-02-29 17:12 UTC, nickludlam commented on Mammoth/Services/Backend/TimelineService.swift
> +        return (result, pagination, cursorId: result.last?.id)
Yeah, initially I had a method which responds with no cursorId, but I was having issues with the way in which cursorId is used to control scrolling and fetches, and it looked sufficiently complicated to make me want to avoid too much disruption, so I adopted it's continued use.

I can look separately at where and how cursorId is used by the NewsFeedViewModel/Controller and at least propose some further changes if not make the changes as part of this PR.

2024-02-29 17:22 UTC, nickludlam commented
I'm not as familiar with the Mastodon API to necessarily know many of the endpoints can take pagination parameters, or respond with `max_id`/`min_id` headers.

The other thing we ought to plan for in this feedback is the future way in which we could use and sync offline data.

2024-07-17 18:02 UTC, closed without merging