MAM-3857-redundant-excessive-custom-emoji-image-requests
TheBLVD/mammoth pull request #479
Opened 2024-03-09 15:23 UTC by derspyy

2024-03-11 17:45 UTC, bnolens requested changes
Nice improvement!!! Please have a look at my comment.

2024-03-11 17:45 UTC, bnolens commented on Mammoth/Models/PostCardModel.swift
> +                self.imagePrefetchToken = prefetcher.prefetchURLs([$0.url], context: [.animatedImageClass: SDAnimatedImageView.self], progress: nil)
Reusing the same `imagePrefetchToken` prop probably not what we wanna do here. 
It's getting reset in each for each iteration and also the prefetrchURL call is an async call and the token should say available until the request completed. Because we want to cancel the request early in some scenarios. 
Wondering if you should store the token in the first place for these emojis?

2024-03-11 17:45 UTC, bnolens commented on Mammoth/Models/UserCardModel.swift
> +            if !SDImageCache.shared.diskImageDataExists(withKey: $0.url.absoluteString) {
Same comment about the token here

2024-03-11 18:19 UTC, derspyy commented on Mammoth/Models/PostCardModel.swift
> +                self.imagePrefetchToken = prefetcher.prefetchURLs([$0.url], context: [.animatedImageClass: SDAnimatedImageView.self], progress: nil)
would it work if i just kept that same download function as before? is that part of the same cache?

2024-03-12 18:11 UTC, bnolens approved these changes
LGTM

2024-03-12 18:11 UTC, merged