MAM-4032-listening-to-audio-not-working
TheBLVD/mammoth pull request #484
Opened 2024-03-10 17:35 UTC by derspyy

2024-03-12 18:20 UTC, bnolens requested changes
Please have a look at my comment

2024-03-12 18:20 UTC, bnolens commented on Mammoth/Views/Cells/PostCardCell/PostCardVideo.swift
> +                let previewImageURL = URL(string: media.previewURL ?? "")
I'd say, unwrapping the optional like in this example would be cleaner
```
if let previewImageURL = URL(string: media.previewURL) {
     previewImage.sd_setImage(with: previewImageURL)
}

2024-03-12 18:33 UTC, derspyy commented on Mammoth/Views/Cells/PostCardCell/PostCardVideo.swift
> +                let previewImageURL = URL(string: media.previewURL ?? "")
you're right.

2024-03-12 18:35 UTC, derspyy commented on Mammoth/Views/Cells/PostCardCell/PostCardVideo.swift
> +                let previewImageURL = URL(string: media.previewURL ?? "")
well, actually, 

```
if let previewImageURL = media.previewURL{
     previewImage.sd_setImage(with: URL(previewImageURL))
}
```

2024-03-12 18:40 UTC, bnolens commented on Mammoth/Views/Cells/PostCardCell/PostCardVideo.swift
> +                let previewImageURL = URL(string: media.previewURL ?? "")
Yes that works too

2024-03-22 13:12 UTC, bnolens approved these changes
LGTM!

2024-03-22 13:12 UTC, merged