MAM-3990-images-in-akkoma-posts-have-wrong-dimensions
TheBLVD/mammoth pull request #485
Opened 2024-03-10 22:39 UTC by derspyy

we need to see if this breaks anything, i made images without metadata fallback to 16:9 with a fit scale. this is how they look:

<img width="314" alt="image" src="https://github.com/TheBLVD/mammoth/assets/65043391/454d936d-0e67-444b-9c3d-3a581e45ab0a">

this is how they compare to akkoma's frontend:

<img width="611" alt="image" src="https://github.com/TheBLVD/mammoth/assets/65043391/a2378d05-1239-41e9-9095-fb89703bf29d">

mastodon images should be untouched.

2024-03-12 19:58 UTC, derspyy commented on Mammoth/Views/Cells/PostCardCell/PostCardImage.swift
> -            if let ratio = self.media?.meta?.original?.aspect {
just noticed that the diff here is horrible. i just changed this first line, the rest is indentation.

2024-03-12 19:58 UTC, derspyy commented on Mammoth/Views/Cells/PostCardCell/PostCardVideo.swift
> -                if let ratio = self.media?.meta?.original?.aspect {
same here

2024-03-25 18:29 UTC, bnolens requested changes
There's an issue where the blurhash image is not the same size as the final image. If that's fixed, I think looks good. 👍 
https://github.com/TheBLVD/mammoth/assets/221925/ee33b753-957c-4b78-80fb-ffc6c8aca467

2024-03-25 18:58 UTC, derspyy commented
i really don't think this is related to my pr (which only concerns images with no metadata and therefore no blurhash), but i can also fix that if you want

2024-03-25 19:00 UTC, bnolens commented
> i really don't think this is related to my pr (which only concerns images with no metadata and therefore no blurhash), but i can also fix that if you want

What about this change you made? https://github.com/TheBLVD/mammoth/pull/485/files#diff-db60f1901e92e5866bdbe16565649da7b8f6e6b3c4888169a3ac93faad313f6cR26

2024-03-26 10:18 UTC, derspyy commented
> > i really don't think this is related to my pr (which only concerns images with no metadata and therefore no blurhash), but i can also fix that if you want
> 
> 
> 
> What about this change you made? https://github.com/TheBLVD/mammoth/pull/485/files#diff-db60f1901e92e5866bdbe16565649da7b8f6e6b3c4888169a3ac93faad313f6cR26

for reference: since i changed the images to FIT instead of FILL, the placeholders with wrong dimensions became more visible. fixed it though

2024-03-27 09:29 UTC, derspyy commented
made it so that only these images will be set to FIT scale.

2024-05-08 20:16 UTC, bnolens approved these changes
LGTM

2024-05-13 16:12 UTC, merged