MAM-3980-use-language-field-in-instancessocial
TheBLVD/mammoth pull request #496
Opened 2024-03-17 16:55 UTC by derspyy

we still need featurekit to take this input into account, though.

2024-03-18 09:21 UTC, bnolens requested changes

2024-03-18 09:24 UTC, derspyy commented on Mammoth/Screens/Registration/SignInViewController.swift
> +            components.queryItems = [URLQueryItem(name: "language", value: NSLocale.current.languageCode)]
is there any difference, if we're checking against our approved list?

2024-03-18 09:24 UTC, derspyy commented on Mammoth/Screens/Registration/SignInViewController.swift
> +            components.queryItems = [URLQueryItem(name: "language", value: NSLocale.current.languageCode)]
asking because docs on these are pretty surface level

2024-03-18 09:29 UTC, bnolens commented on Mammoth/Screens/Registration/SignInViewController.swift
> +            components.queryItems = [URLQueryItem(name: "language", value: NSLocale.current.languageCode)]
Mainly saying this because you use `NSLocale.preferredLanguages[0]` in your `if` statement but then use `NSLocale.current.languageCode` in the URL query. That doesn't make sense. 
I would change this a bit and use `l10n.getCurrentLocale()` in both cases after making that method public.

2024-03-18 09:31 UTC, derspyy commented on Mammoth/Screens/Registration/SignInViewController.swift
> +            components.queryItems = [URLQueryItem(name: "language", value: NSLocale.current.languageCode)]
oh, i'm using languageCode because that strips the region, so "pt-BR" would only give "pt", which is what instances.social takes as an input

2024-03-18 09:35 UTC, bnolens commented on Mammoth/Screens/Registration/SignInViewController.swift
> +            components.queryItems = [URLQueryItem(name: "language", value: NSLocale.current.languageCode)]
Oh, I see. Ok in that case it does make sense. Wondering if you need the if statement around this? Do we only want to enable this if we support the language for UI localization too?

2024-03-18 09:39 UTC, derspyy commented on Mammoth/Screens/Registration/SignInViewController.swift
> +            components.queryItems = [URLQueryItem(name: "language", value: NSLocale.current.languageCode)]
the idea was that the experience would be unchanged for people using unsupported languages, since the UI would still be in english

2024-03-19 13:32 UTC, bnolens approved these changes
LGTM

2024-03-19 13:32 UTC, merged