MAM-4076-2xtab-scrollup-when-all-content-is-loaded
TheBLVD/mammoth pull request #537
Opened 2024-03-29 17:07 UTC by bnolens

https://linear.app/theblvd/issue/MAM-4076/2xtab-scrollup-when-all-content-is-loaded

2024-03-30 11:21 UTC, derspyy approved these changes
looks good : )

2024-04-02 21:03 UTC, derspyy requested changes
addressed some concerns.

2024-04-02 21:09 UTC, bnolens commented on Mammoth/Services/Backend/MastodonKit/Requests/Timelines.swift
Looks like moth.social can return 120 posts (might be more even). So why not ask for more? If the server caps it at 40, we're still good.

2024-04-03 16:13 UTC, bnolens commented on Mammoth/Services/Backend/MastodonKit/Requests/Timelines.swift
That's a good point. There was an issue with the current logic. The limit was ignored when passing a limit inside the `max` or `min` case, and the default (20) was used. I changed the code so the limit inside these cases is considered. https://github.com/TheBLVD/mammoth/pull/537/files#diff-b0738e41b5a48946cba9e561892ab40316b1f6254f651758fabdec4dfa6f4027R105

2024-04-03 16:15 UTC, bnolens commented
Going to merge this PR. Feel free to comment on it, and I'll address issues in separate PRs

2024-04-03 16:15 UTC, merged