MAM-4132-improvements-to-webview
TheBLVD/mammoth pull request #569
Opened 2024-05-10 00:36 UTC by derspyy

2024-05-13 10:22 UTC, derspyy commented
making this a draft because i want to look into a crash.

2024-05-13 12:51 UTC, bnolens requested changes
Please check my notes

2024-05-13 20:41 UTC, derspyy commented on Mammoth/Views/Cells/PostCardCell/PostCardWebview.swift
> +                placeholder = UnifiedImage(blurHash: blurhash, size: .init(width: 32, height: 32))
link card blurhashes aren't taken into account in that function, though i'll add it. thanks!

2024-05-14 08:25 UTC, bnolens approved these changes
LGTM

2024-05-14 08:26 UTC, merged