MAM-3683-full-usernames-not-showing-in-replies-from-same-instance-as
TheBLVD/mammoth pull request #575
Opened 2024-05-24 02:15 UTC by derspyy

2024-05-24 15:00 UTC, bnolens requested changes
Please check my notes

2024-05-24 15:22 UTC, derspyy commented on Mammoth/Screens/DetailScreen/DetailViewModel.swift
> +    func fixUsername(postCard: PostCardModel, userInstance: String) -> PostCardModel {
what the detailview reads is userTag. you can check that it's working when you open a post in detail view.

2024-05-24 15:23 UTC, derspyy commented on Mammoth/Screens/DetailScreen/DetailViewModel.swift
> +    func fixUsername(postCard: PostCardModel, userInstance: String) -> PostCardModel {
> Try to rename this func to something less generic

i was thinking something like "normalizeUsertag"?

2024-05-24 15:32 UTC, bnolens commented on Mammoth/Screens/DetailScreen/DetailViewModel.swift
> +    func fixUsername(postCard: PostCardModel, userInstance: String) -> PostCardModel {
> what the detailview reads is userTag. you can check that it's working when you open a post in detail view.

But what you really want to use is `fullUserTag`, no?

2024-05-24 15:39 UTC, derspyy commented on Mammoth/Screens/DetailScreen/DetailViewModel.swift
> +    func fixUsername(postCard: PostCardModel, userInstance: String) -> PostCardModel {
no... full always contains the domain. the correct behavior is the regular userTag showing the domain only when it's different from yours

2024-05-24 15:40 UTC, derspyy commented on Mammoth/Screens/DetailScreen/DetailViewModel.swift
> +    func fixUsername(postCard: PostCardModel, userInstance: String) -> PostCardModel {
but that breaks because we use a remote server to get replies.

2024-05-24 15:42 UTC, bnolens commented on Mammoth/Screens/DetailScreen/DetailViewModel.swift
> +    func fixUsername(postCard: PostCardModel, userInstance: String) -> PostCardModel {
I see. In that case, you should store this in PostCardModel

2024-05-24 15:47 UTC, derspyy commented on Mammoth/Screens/DetailScreen/DetailViewModel.swift
> +    func fixUsername(postCard: PostCardModel, userInstance: String) -> PostCardModel {
okay, cool. want me to rework the PR later today?

2024-05-24 15:50 UTC, derspyy commented on Mammoth/Screens/DetailScreen/DetailViewModel.swift
> +    func fixUsername(postCard: PostCardModel, userInstance: String) -> PostCardModel {
the only issue is that i wouldn't want this function to be run everywhere, only when we load replies remotely (and maybe profiles, also?)

2024-06-07 15:10 UTC, bnolens commented on Mammoth/Screens/Composer/NewPostViewController.swift
> +        // closest regex i derived from mastodon's:
i -> if

2024-06-07 15:11 UTC, bnolens approved these changes
Please fix the typo but good to merge after fixing it

2024-06-07 16:30 UTC, merged