Project Configuration
TheBLVD/mammoth pull request #585
Opened 2024-06-09 18:54 UTC by dimitribouniol

I noticed that:
a) we can define the ruby version locally to minimize version drift between developers, and 
b) ArkanaKeys was not part of the Xcode project, so I added it as a dependency.

2024-06-09 18:54 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/TheBLVD/mammoth?pullRequest=585) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/TheBLVD/mammoth?pullRequest=585) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/TheBLVD/mammoth?pullRequest=585) it.</sub>

2024-06-10 16:31 UTC, dimitribouniol commented on Mammoth.xcodeproj/project.pbxproj
> +		655609B72C1757AA004233BC /* README.md */ = {isa = PBXFileReference; lastKnownFileType = net.daringfireball.markdown; path = README.md; sourceTree = "<group>"; };
This makes accessing the README easy in Xcode. It's not added to the compiled binary:
<img width="672" alt="image" src="https://github.com/TheBLVD/mammoth/assets/225505/c204dfba-a170-42e7-a3ca-11072a2de66c">

2024-06-11 21:28 UTC, rileyhCode requested changes
It's great to get some fresh eyes on the setup instructions. Pls review my comments, and then make changes and/or reply as you see fit. Thx!

2024-06-11 21:28 UTC, rileyhCode commented on README.md
> +4. Install a compatible version of ruby, and continue the steps above:
Should this be "…continue the steps below:"?

2024-06-11 21:28 UTC, rileyhCode commented on README.md
> -4. install current Ruby version `rbenv install 3.2.1`
Even though it can be dicey to specify a version of ruby here, there is an implication that this is a "known working version". I wonder if we should either keep this instruction, or… at least add a comment indicating this is a known working version.

(though… above you set a version of 3.3.2 - so maybe that works?) Hm. Just trying to make it easiest for someone new coming onto the project.

2024-06-11 21:29 UTC, dimitribouniol commented on README.md
> +4. Install a compatible version of ruby, and continue the steps above:
No, above since you would need to bundle install and bin/arkana to finish the process

2024-06-11 21:31 UTC, dimitribouniol commented on README.md
> -4. install current Ruby version `rbenv install 3.2.1`
Yeah, I verified 3.3.2 is a known working version, so it shouldn’t be an issue from this point forward since rbenv will use that version since it’s part of the repo now — everyone will just end up using that version.

2024-06-12 16:36 UTC, dimitribouniol commented on README.md
> +4. Install a compatible version of ruby, and continue the steps above:
This now links back to the requirements section to make it extra clear!

2024-06-12 16:47 UTC, rileyhCode approved these changes
Looks good to me.

2024-06-12 18:15 UTC, merged