sub-club: wip integration.
TheBLVD/mammoth pull request #591
Opened 2024-06-19 01:38 UTC by derspyy

- [x] detect SC accounts and main accounts linking SC.
- [x] show subscribe button on both accounts.
- [x] show subscription post tab on main acc.
- [ ] polish subscription flow.
- [ ] detect a SC redirect.

2024-06-19 10:38 UTC, bnolens requested changes
Great! Please check my notes

2024-06-19 10:38 UTC, bnolens commented on Mammoth/Models/UserCardModel.swift
> +        self.tippable = account.acct.hasSuffix("social-proxy.com")
Would be good to put this string in a constant so it's easy to update when we change domains. Maybe in .env?

2024-06-19 10:38 UTC, bnolens commented on Mammoth/Models/PostCardModel.swift
> +    var tipAccount: Bool {
Our booleans in here mostly start with `is`. Would make sense to use `isTipAccount` here too

2024-06-19 10:38 UTC, bnolens commented on Mammoth/Models/UserCardModel.swift
> +    let tippable: Bool
Idem (`isTippable`)?

2024-06-19 10:38 UTC, bnolens commented on Mammoth/Models/UserCardModel.swift
> +            if let s = field.value.matchingStrings(regex: "https://social-proxy.com/users/([a-z0-9-_]+)").first?[1] {
Item, don't hardcode the social-proxy url

2024-06-19 10:38 UTC, bnolens commented on Mammoth/Screens/ProfileScreen/Views/ProfileHeader.swift
>          let joined_on = user.joinedOn?.toString(dateStyle: .short, timeStyle: .none) ?? ""
Not your change, but this variable should be camelcase. You mind changing it?

2024-06-19 10:38 UTC, bnolens commented on Mammoth/Screens/ProfileScreen/Views/ProfileHeader.swift
> +                if let url = URL(string: "https://social-proxy.com/subscribe/to/\(user.username)?amount=500&currency=USD") {
Item, try not to hardcode the domain

2024-06-19 10:38 UTC, bnolens commented on Mammoth/Screens/ProfileScreen/Views/ProfileHeader.swift
> +                if let url = URL(string: "https://social-proxy.com/subscribe/to/\(user.username)?amount=500&currency=USD") {
The new url is actually `https://social-proxy.com/@\(user.username)/subscribe?amount=500&currency=USD`, please update to that. The old one will still work for a while though

2024-06-19 10:38 UTC, bnolens commented on Mammoth/Screens/ProfileScreen/Views/ProfileHeader.swift
> +                if let username = user.tippableAccount, let url = URL(string: "https://social-proxy.com/subscribe/to/\(username)?amount=500&currency=USD") {
Item url changes

2024-06-19 10:42 UTC, bnolens commented
Wondering how well the following status gets updates after returning from the social-proxy.com review. Is it always correctly saying "Following"? If not, we should force a relationship sync when coming back.

2024-06-19 10:45 UTC, bnolens commented
I just realized this is still a draft. I might have been a bit quick in reviewing this, but progress looks good!

2024-06-19 11:17 UTC, derspyy commented
> Wondering how well the following status gets updates after returning from the social-proxy.com review. Is it always correctly saying "Following"? If not, we should force a relationship sync when coming back.

agreed. this is part of the subscription flow that i'm still planning on polishing.

2024-06-19 11:19 UTC, derspyy commented
also agreed on not hardcoding the domain. i'll work on that

2024-06-20 01:10 UTC, derspyy commented
update: i still need to test the following status update. i couldn't because of the issues when subscribing.

2024-06-20 17:59 UTC, bnolens commented on Mammoth/Screens/ProfileScreen/Views/ProfileHeader.swift
> +                if let username = user.tippableAccount, let url = URL(string: "https://" + ArkanaKeys.Global().subClubDomain + "/@\(username)/subscribe?callback=mammoth://social-proxy=\(username)&amo
This path should be `https://subclub.social/@premiumUsername/subscribe?callback=mammoth://social-proxy&id=accountUsername&amount=500&currency=USD`

reference in icecubes: https://github.com/Dimillian/IceCubesApp/commit/3fbfecb171a4c12a78bafbd7f280b188239a2353#diff-3e9e838a1912ac03de6d850047cf6f7188e589934090657edafefc581bc5c850R126

2024-06-20 18:05 UTC, derspyy commented on Mammoth/Screens/ProfileScreen/Views/ProfileHeader.swift
> +                if let username = user.tippableAccount, let url = URL(string: "https://" + ArkanaKeys.Global().subClubDomain + "/@\(username)/subscribe?callback=mammoth://social-proxy=\(username)&amo
i added the username to the callback so that we could use it to follow the correct account right away

2024-06-20 18:18 UTC, derspyy commented on Mammoth/Screens/ProfileScreen/Views/ProfileHeader.swift
> +                if let username = user.tippableAccount, let url = URL(string: "https://" + ArkanaKeys.Global().subClubDomain + "/@\(username)/subscribe?callback=mammoth://social-proxy=\(username)&amo
(take a look at the SceneDelegate impl)

2024-06-20 19:51 UTC, bnolens commented on Mammoth/Screens/ProfileScreen/Views/ProfileHeader.swift
> +                if let username = user.tippableAccount, let url = URL(string: "https://" + ArkanaKeys.Global().subClubDomain + "/@\(username)/subscribe?callback=mammoth://social-proxy=\(username)&amo
Oh I see, great. 
But there's still an issue with the usernames you pass. The username after the @ (premium usename) should be the acct of the creator, so without `@subclub.social`. 
You should also pass the full acct handle of the currently logged-in account as a URL parameter with key `id`. (see example above)

2024-06-21 01:40 UTC, derspyy commented
tomorrow i'll check tippableAccount to see if i can store the domain separately from the username, because i need it for the callback...

2024-06-21 14:06 UTC, derspyy commented
(adding the domain and then removing it right afterwards is just a quick hack i made this morning for it to work, i'll probably end up storing the username by itself and just adding it back in the callback

2024-08-30 08:47 UTC, merged